import type { DisplayText, ExperimentRow, JobRow, NotificationRow, ResultRow, ViewId } from './types';

function text(ko: string, en: string): DisplayText {
  return { ko, en };
}

export const operatorProfile = {
  name: 'Ops Admin',
  tenant: 'tenant#1 · ops_admin',
  environment: 'STG',
  currentShop: '샘플카페 · 본점',
} as const;

export const jobsData: JobRow[] = [
  {
    id: 'job-9812',
    orderId: 'order#2048',
    productName: '스타벅스 드립백 1팩 · 콜롬비아 로스트',
    shopName: '강남점',
    quantity: 40,
    source: 'naver',
    status: 'running',
    attempts: 1,
    maxAttempts: 3,
    queuedAt: '2026-04-24T10:14:02+09:00',
    timeScope: '24h',
    detail: {
      targetUnitPrice: 20080,
      queueDepth: 0,
      durationSeconds: 4.2,
      policy: text('최적 결과 선택 → 알림 발송', 'best_result → notification'),
      keptResults: 20,
      totalResults: 20,
      rawPayload: {
        source: 'naver',
        method: 'shopping_api',
        idempotencyKey: 'ord-2048:naver:202604241014',
        targetUnitPrice: 20080,
      },
      timeline: [
        { id: 'j9812-1', title: text('수집 작업 대기열 등록', 'order collect queued'), detail: 'POST /procurement/orders/2048/collect', timestamp: '2026-04-24T10:13:55+09:00', tone: 'info' },
        { id: 'j9812-2', title: text('디스패처 워커 배정', 'dispatcher assigned worker'), detail: text('워커 큐 collection.naver.standard', 'worker queue=collection.naver.standard'), timestamp: '2026-04-24T10:13:56+09:00', tone: 'success' },
        { id: 'j9812-3', title: text('후보 수집 진행 중', 'candidate collection running'), detail: text('display=20 · 유사도 정렬 · compare_eligible 검증 활성', 'display=20 · sim sort · compare_eligible validators active'), timestamp: '2026-04-24T10:14:02+09:00', tone: 'info' },
      ],
    },
  },
  {
    id: 'job-9811',
    orderId: 'order#2047',
    productName: '일리 에스프레소 100캡슐 · Classico',
    shopName: '본점',
    quantity: 8,
    source: 'naver',
    status: 'retry-scheduled',
    attempts: 2,
    maxAttempts: 3,
    queuedAt: '2026-04-24T10:07:43+09:00',
    nextRetryAt: '2026-04-24T10:16:14+09:00',
    lastErrorCode: 'NAVER_RATE_LIMIT',
    lastErrorMessage: text('429 요청 한도 초과', '429 too many requests'),
    timeScope: '24h',
    detail: {
      targetUnitPrice: 19450,
      queueDepth: 2,
      durationSeconds: null,
      policy: text('지수 백오프 재시도', 'retry_backoff.exponential'),
      keptResults: null,
      totalResults: null,
      rawPayload: {
        source: 'naver',
        attempt: 2,
        backoffSeconds: 180,
        reason: 'NAVER_RATE_LIMIT',
      },
      timeline: [
        { id: 'j9811-1', title: text('1차 시도 대기열 등록', 'attempt #1 queued'), detail: text('주문 수집 요청이 접수되었습니다.', 'order collect accepted'), timestamp: '2026-04-24T10:07:43+09:00', tone: 'info' },
        { id: 'j9811-2', title: text('요청 한도 감지', 'rate limit detected'), detail: text('shopping_api 429 요청 한도 초과', 'shopping_api 429 too many requests'), timestamp: '2026-04-24T10:08:10+09:00', tone: 'warning' },
        { id: 'j9811-3', title: text('재시도 예약', 'retry scheduled'), detail: text('백오프 180초 · collection.retry 큐', 'backoff=180s · queue=collection.retry'), timestamp: '2026-04-24T10:08:11+09:00', tone: 'warning' },
      ],
    },
  },
  {
    id: 'job-9809',
    orderId: 'order#2045',
    productName: '네스프레소 호환캡슐 볼루토 · 200개입',
    shopName: '판교점',
    quantity: 12,
    source: 'naver',
    status: 'failed',
    attempts: 3,
    maxAttempts: 3,
    queuedAt: '2026-04-24T09:42:11+09:00',
    finishedAt: '2026-04-24T09:44:36+09:00',
    lastErrorCode: 'NAVER_NO_RESULT',
    lastErrorMessage: text('정규화 이후 검색 결과 0건', 'No results after query normalization'),
    timeScope: '24h',
    detail: {
      targetUnitPrice: 9150,
      queueDepth: 0,
      durationSeconds: 145,
      policy: text('최대 시도 후 DLQ 이동', 'dead_letter.after_max_attempts'),
      keptResults: 0,
      totalResults: 0,
      rawPayload: {
        normalizedQuery: '네스프레소 볼루토 호환캡슐 200개입',
        attempts: 3,
        deadLettered: true,
      },
      timeline: [
        { id: 'j9809-1', title: text('1차 시도 결과 없음', 'attempt #1 no result'), detail: text('정규화 후 후보 0건 반환', '0 candidates returned after normalization'), timestamp: '2026-04-24T09:42:40+09:00', tone: 'warning' },
        { id: 'j9809-2', title: text('2차 시도 결과 없음', 'attempt #2 no result'), detail: text('브랜드 fallback으로 쿼리 조정', 'query adjusted with brand fallback'), timestamp: '2026-04-24T09:43:21+09:00', tone: 'warning' },
        { id: 'j9809-3', title: text('DLQ 이동', 'dead-lettered'), detail: text('최대 시도 도달 · 운영자 재확인 필요', 'max attempts reached · operator recheck needed'), timestamp: '2026-04-24T09:44:36+09:00', tone: 'danger' },
      ],
    },
  },
  {
    id: 'job-9808',
    orderId: 'order#2044',
    productName: '원두 하리오 V60 필터 02 · 화이트 100매',
    shopName: '강남점',
    quantity: 6,
    source: 'naver',
    status: 'partial',
    attempts: 2,
    maxAttempts: 3,
    queuedAt: '2026-04-24T09:40:18+09:00',
    finishedAt: '2026-04-24T09:41:03+09:00',
    lastErrorCode: 'PARSER_PARTIAL',
    lastErrorMessage: text('compare_eligible=false로 6개 후보 제외', '6 items dropped by compare_eligible=false'),
    timeScope: '24h',
    detail: {
      targetUnitPrice: 7350,
      queueDepth: 0,
      durationSeconds: 45,
      policy: text('최적 결과가 있으면 부분 결과 허용', 'allow_partial_if_best_exists'),
      keptResults: 14,
      totalResults: 20,
      rawPayload: {
        droppedReasons: ['QTY_MISMATCH', 'SHIPPING_UNKNOWN'],
        kept: 14,
        total: 20,
      },
      timeline: [
        { id: 'j9808-1', title: text('후보 파싱 완료', 'candidate parse completed'), detail: text('소스에서 20개 행 파싱', '20 rows parsed from source'), timestamp: '2026-04-24T09:40:51+09:00', tone: 'success' },
        { id: 'j9808-2', title: text('검증기가 부분 행 제외', 'validators removed partial rows'), detail: text('compare_eligible 규칙으로 6개 행 거부', '6 rows rejected by compare_eligible rules'), timestamp: '2026-04-24T09:40:59+09:00', tone: 'warning' },
        { id: 'j9808-3', title: text('부분 결과 승인', 'partial result accepted'), detail: text('최적 결과는 보존하고 알림은 재확인으로 낮춤', 'best result preserved, notification downgraded to recheck'), timestamp: '2026-04-24T09:41:03+09:00', tone: 'warning' },
      ],
    },
  },
  {
    id: 'job-9807',
    orderId: 'order#2043',
    productName: '우유거품기 배터리식 · 화이트',
    shopName: '본점',
    quantity: 3,
    source: 'naver',
    status: 'succeeded',
    attempts: 1,
    maxAttempts: 3,
    queuedAt: '2026-04-24T09:37:44+09:00',
    finishedAt: '2026-04-24T09:38:02+09:00',
    timeScope: '24h',
    detail: {
      targetUnitPrice: 6020,
      queueDepth: 0,
      durationSeconds: 18,
      policy: text('최적 결과 선택 시 완료', 'complete_if_best_result_selected'),
      keptResults: 18,
      totalResults: 18,
      rawPayload: {
        source: 'naver',
        bestResultId: 'result-58798',
        savedPercent: 18.7,
      },
      timeline: [
        { id: 'j9807-1', title: text('수집 완료', 'collection finished'), detail: text('적격 결과 18개 보관', '18 eligible results kept'), timestamp: '2026-04-24T09:38:02+09:00', tone: 'success' },
        { id: 'j9807-2', title: text('최적 결과 선택', 'best result selected'), detail: 'result-58798 → procurement.best_result', timestamp: '2026-04-24T09:38:02+09:00', tone: 'success' },
      ],
    },
  },
  {
    id: 'job-9806',
    orderId: 'order#2042',
    productName: '테이크아웃 컵 12oz 1000개 · 이중벽',
    shopName: '판교점',
    quantity: 4,
    source: 'naver',
    status: 'queued',
    attempts: 0,
    maxAttempts: 3,
    queuedAt: '2026-04-24T09:33:20+09:00',
    timeScope: '24h',
    detail: {
      targetUnitPrice: 158,
      queueDepth: 3,
      durationSeconds: null,
      policy: text('동시 실행 제한으로 대기', 'queued_due_to_concurrency_limit'),
      keptResults: null,
      totalResults: null,
      rawPayload: {
        queueDepth: 3,
        workerPool: 'collection.naver.standard',
        priority: 'normal',
      },
      timeline: [
        { id: 'j9806-1', title: text('활성 워커 뒤에 대기', 'queued behind active workers'), detail: text('워커 동시 실행 한도 도달', 'worker concurrency limit reached'), timestamp: '2026-04-24T09:33:20+09:00', tone: 'neutral' },
      ],
    },
  },
  {
    id: 'job-9788',
    orderId: 'order#2034',
    productName: '콜드브루 파우치 1L · 10개입',
    shopName: '본점',
    quantity: 5,
    source: 'coupang',
    status: 'succeeded',
    attempts: 1,
    maxAttempts: 3,
    queuedAt: '2026-04-21T16:11:02+09:00',
    finishedAt: '2026-04-21T16:11:44+09:00',
    timeScope: '7d',
    detail: {
      targetUnitPrice: 7120,
      queueDepth: 0,
      durationSeconds: 42,
      policy: text('실험 소스는 알림에서 제외', 'experiment_source_excluded_from_notifications'),
      keptResults: 9,
      totalResults: 9,
      rawPayload: {
        source: 'coupang',
        method: 'parser_upload',
        experiment: true,
      },
      timeline: [
        { id: 'j9788-1', title: text('파서 배치 업로드', 'parser batch uploaded'), detail: text('후보 결과 9개를 실험 버킷에 저장', '9 candidate results accepted into experiment bucket'), timestamp: '2026-04-21T16:11:44+09:00', tone: 'success' },
      ],
    },
  },
];

export const resultsData: ResultRow[] = [
  {
    id: 'result-58821',
    orderId: 'order#2048',
    jobId: 'job-9812',
    productName: '스타벅스 드립백 1팩 · 콜롬비아 로스트',
    mallName: '스타벅스공식몰',
    sellerCode: 'mall_id:100045',
    source: 'naver',
    method: 'shopping_api',
    perUnitPrice: 18200,
    listedPrice: 728000,
    shippingFee: 0,
    compareEligible: true,
    collectedAt: '2026-04-24T10:14:06+09:00',
    timeScope: '24h',
    savingsRate: 9.4,
    unitCount: 40,
    unitLabel: '개',
    isBest: true,
    detail: {
      targetUnitPrice: 20080,
      rawPayload: {
        sourceMethod: 'shopping_api',
        externalOfferId: 'nv_47812044',
        collectedAt: '2026-04-24T10:14:06+09:00',
        compareEligible: true,
      },
      siblings: [
        { id: 'rank-1', seller: '스타벅스공식몰', mall: '네이버 쇼핑', perUnitPrice: 18200, eligible: true },
        { id: 'rank-2', seller: '커피마트몰', mall: '네이버 쇼핑', perUnitPrice: 18450, eligible: true },
        { id: 'rank-3', seller: '베러카페몰', mall: '네이버 쇼핑', perUnitPrice: 18710, eligible: true },
      ],
      validatorNotes: [
        text('모든 검증 통과', 'all validators passed'),
        text('무료배송 감지', 'free shipping detected'),
        text('공식몰 우선순위 적용', 'official mall prioritized'),
      ],
      notificationId: 'delivery-88421',
    },
  },
  {
    id: 'result-58820',
    orderId: 'order#2048',
    jobId: 'job-9812',
    productName: '스타벅스 드립백 1팩 · 콜롬비아 로스트',
    mallName: '커피마트몰',
    sellerCode: 'mall_id:200891',
    source: 'naver',
    method: 'shopping_api',
    perUnitPrice: 18450,
    listedPrice: 738000,
    shippingFee: 0,
    compareEligible: true,
    collectedAt: '2026-04-24T10:14:05+09:00',
    timeScope: '24h',
    savingsRate: 8.1,
    unitCount: 40,
    unitLabel: '개',
    isBest: false,
    detail: {
      targetUnitPrice: 20080,
      rawPayload: {
        sourceMethod: 'shopping_api',
        externalOfferId: 'nv_47812041',
        compareEligible: true,
      },
      siblings: [],
      validatorNotes: [text('적격 후보로 보관', 'kept as eligible sibling')],
      notificationId: null,
    },
  },
  {
    id: 'result-58812',
    orderId: 'order#2044',
    jobId: 'job-9808',
    productName: '하리오 V60 필터 02 · 화이트 100매',
    mallName: '베러카페몰',
    sellerCode: 'mall_id:330221',
    source: 'naver',
    method: 'shopping_api',
    perUnitPrice: 6900,
    listedPrice: 41400,
    shippingFee: 0,
    compareEligible: false,
    partialReason: 'QTY_MISMATCH',
    collectedAt: '2026-04-24T09:41:01+09:00',
    timeScope: '24h',
    savingsRate: 6.1,
    unitCount: 6,
    unitLabel: '개',
    isBest: false,
    detail: {
      targetUnitPrice: 7350,
      rawPayload: {
        parsedQty: 80,
        expectedQty: 100,
        compareEligible: false,
      },
      siblings: [],
      validatorNotes: [text('예상 100매, 파싱 80매', 'expected 100 sheets, parsed 80 sheets')],
      notificationId: null,
    },
  },
  {
    id: 'result-58798',
    orderId: 'order#2043',
    jobId: 'job-9807',
    productName: '우유거품기 배터리식 · 화이트',
    mallName: '주방대장',
    sellerCode: 'mall_id:552301',
    source: 'naver',
    method: 'shopping_api',
    perUnitPrice: 4880,
    listedPrice: 14640,
    shippingFee: 0,
    compareEligible: true,
    collectedAt: '2026-04-24T09:38:02+09:00',
    timeScope: '24h',
    savingsRate: 18.7,
    unitCount: 3,
    unitLabel: '개',
    isBest: true,
    detail: {
      targetUnitPrice: 6020,
      rawPayload: {
        sourceMethod: 'shopping_api',
        compareEligible: true,
        ranking: 1,
      },
      siblings: [
        { id: 'frother-1', seller: '주방대장', mall: '네이버 쇼핑', perUnitPrice: 4880, eligible: true },
        { id: 'frother-2', seller: '홈카페마트', mall: '네이버 쇼핑', perUnitPrice: 5290, eligible: true },
      ],
      validatorNotes: [text('최적 셀러 선택', 'best seller selected'), text('알림 발행', 'notification emitted')],
      notificationId: 'delivery-88398',
    },
  },
  {
    id: 'result-58772',
    orderId: 'order#2040',
    jobId: 'job-9804',
    productName: '테이크아웃 컵 12oz · 이중벽',
    mallName: '패키지플러스',
    sellerCode: 'mall_id:771123',
    source: 'naver',
    method: 'shopping_api',
    perUnitPrice: 148,
    listedPrice: 148000,
    shippingFee: 0,
    compareEligible: false,
    partialReason: 'PARSER_AMBIGUOUS',
    collectedAt: '2026-04-24T09:11:02+09:00',
    timeScope: '24h',
    savingsRate: null,
    unitCount: 1000,
    unitLabel: '개',
    isBest: false,
    detail: {
      targetUnitPrice: 158,
      rawPayload: {
        ambiguousOption: '2겹/3겹 구분 불명',
        compareEligible: false,
      },
      siblings: [],
      validatorNotes: [text('옵션 라벨이 모호함', 'variant labels were ambiguous')],
      notificationId: null,
    },
  },
  {
    id: 'result-exp-1042',
    orderId: 'exp#1042',
    jobId: 'exp-run-1042',
    productName: '커피머신 세정제 · 쿠팡 비교 샘플',
    mallName: '쿠팡 파트너셀러',
    sellerCode: 'seller:cp-4102',
    source: 'coupang',
    method: 'parser_upload',
    perUnitPrice: 7420,
    listedPrice: 311640,
    shippingFee: 0,
    compareEligible: true,
    collectedAt: '2026-04-24T10:02:14+09:00',
    timeScope: '24h',
    savingsRate: null,
    unitCount: 42,
    unitLabel: '개',
    isBest: false,
    detail: {
      targetUnitPrice: 7000,
      rawPayload: {
        sourceMethod: 'parser_upload',
        experiment: true,
        excludedFromNotifications: true,
      },
      siblings: [],
      validatorNotes: [text('격리된 실험 행', 'isolated experiment row'), text('주요 KPI에서 제외', 'excluded from primary KPI strip')],
      notificationId: null,
    },
  },
];

export const notificationsData: NotificationRow[] = [
  {
    id: 'delivery-88421',
    eventCode: 'procurement.best_result',
    orderId: 'order#2048',
    jobId: 'job-9812',
    resultId: 'result-58821',
    outboxId: 'outbox#77102',
    channel: 'alimtalk',
    templateName: 'procurement_best_v3',
    templateVersion: 'v5',
    recipientName: '김사장',
    recipientId: 'recipient#411',
    recipientPhone: '+82 10-****-2048',
    status: 'sending',
    sentAt: '2026-04-24T10:14:08+09:00',
    timeScope: '24h',
    fallbackFrom: null,
    detail: {
      timeline: [
        { id: 'n88421-1', title: text('주문 대기열 등록', 'order queued'), detail: 'POST /procurement/orders/2048/collect', timestamp: '2026-04-24T10:13:55+09:00', tone: 'info' },
        { id: 'n88421-2', title: text('최적 결과 선택', 'best result selected'), detail: text('result-58821을 order.best_result_id에 저장', 'result-58821 saved to order.best_result_id'), timestamp: '2026-04-24T10:14:06+09:00', tone: 'success' },
        { id: 'n88421-3', title: text('아웃박스 발행', 'outbox published'), detail: text('디스패처가 delivery-88421 생성', 'Dispatcher created delivery-88421'), timestamp: '2026-04-24T10:14:07+09:00', tone: 'success' },
        { id: 'n88421-4', title: text('제공사 시도 진행 중', 'provider attempt in flight'), detail: text('Kakao Biz 계정 kko_main · timeout 6초', 'Kakao Biz account kko_main · timeout 6s'), timestamp: '2026-04-24T10:14:08+09:00', tone: 'info' },
      ],
      renderedVariables: {
        shop_name: '샘플카페 강남점',
        product_name: '스타벅스 드립백 1팩 · 콜롬비아 로스트',
        best_mall: '스타벅스공식몰',
        best_per_unit_price: 18200,
        qty: 40,
        total_price: 728000,
      },
      providerAttempts: [
        { id: 'attempt-1', channel: 'alimtalk', status: 'sending', provider: 'Kakao Biz', timestamp: '2026-04-24T10:14:08+09:00', detail: text('provider_message_id 대기 중', 'provider_message_id pending') },
      ],
    },
  },
  {
    id: 'delivery-88398',
    eventCode: 'procurement.best_result',
    orderId: 'order#2043',
    jobId: 'job-9807',
    resultId: 'result-58798',
    outboxId: 'outbox#77088',
    channel: 'alimtalk',
    templateName: 'procurement_best_v3',
    templateVersion: 'v5',
    recipientName: '이대표',
    recipientId: 'recipient#208',
    recipientPhone: '+82 10-****-0921',
    status: 'delivered',
    sentAt: '2026-04-24T09:38:14+09:00',
    timeScope: '24h',
    fallbackFrom: null,
    detail: {
      timeline: [
        { id: 'n88398-1', title: text('아웃박스 발행', 'outbox emitted'), detail: text('알림톡 우선순위 정책 적용', 'policy resolved with alimtalk priority'), timestamp: '2026-04-24T09:38:03+09:00', tone: 'success' },
        { id: 'n88398-2', title: text('제공사 접수', 'provider accepted'), detail: text('Kakao Biz 요청 420ms 내 접수', 'Kakao Biz request accepted in 420ms'), timestamp: '2026-04-24T09:38:14+09:00', tone: 'success' },
        { id: 'n88398-3', title: text('전달 확인', 'delivery confirmed'), detail: text('callback 수신 → delivered', 'callback received → delivered'), timestamp: '2026-04-24T09:38:27+09:00', tone: 'success' },
      ],
      renderedVariables: {
        shop_name: '샘플카페 본점',
        product_name: '우유거품기 배터리식 · 화이트',
        best_per_unit_price: 4880,
      },
      providerAttempts: [
        { id: 'attempt-1', channel: 'alimtalk', status: 'delivered', provider: 'Kakao Biz', timestamp: '2026-04-24T09:38:14+09:00', detail: text('callback 지연 13초', 'callback delay 13s') },
      ],
    },
  },
  {
    id: 'delivery-88391',
    eventCode: 'procurement.recheck_required',
    orderId: 'order#2044',
    jobId: 'job-9808',
    resultId: null,
    outboxId: 'outbox#77085',
    channel: 'alimtalk',
    templateName: 'procurement_recheck_v2',
    templateVersion: 'v2',
    recipientName: '박실장',
    recipientId: 'recipient#344',
    recipientPhone: '+82 10-****-7421',
    status: 'delivered',
    sentAt: '2026-04-24T09:41:22+09:00',
    timeScope: '24h',
    fallbackFrom: null,
    detail: {
      timeline: [
        { id: 'n88391-1', title: text('부분 결과 감지', 'partial result detected'), detail: text('compare_eligible 행 누락 → 재확인 이벤트', 'compare_eligible rows missing → recheck event'), timestamp: '2026-04-24T09:41:03+09:00', tone: 'warning' },
        { id: 'n88391-2', title: text('메시지 렌더링', 'message rendered'), detail: 'template procurement_recheck_v2', timestamp: '2026-04-24T09:41:10+09:00', tone: 'info' },
        { id: 'n88391-3', title: text('전달 확인', 'delivery confirmed'), detail: text('알림톡 전달 완료', 'alimtalk delivered'), timestamp: '2026-04-24T09:41:22+09:00', tone: 'success' },
      ],
      renderedVariables: {
        order_id: 'order#2044',
        issue: 'compare_eligible rows removed',
        kept_results: 14,
      },
      providerAttempts: [
        { id: 'attempt-1', channel: 'alimtalk', status: 'delivered', provider: 'Kakao Biz', timestamp: '2026-04-24T09:41:22+09:00', detail: 'message_type=recheck' },
      ],
    },
  },
  {
    id: 'delivery-88322',
    eventCode: 'procurement.best_result',
    orderId: 'order#2039',
    jobId: 'job-9798',
    resultId: 'result-58702',
    outboxId: 'outbox#77021',
    channel: 'lms',
    templateName: 'procurement_best_lms',
    templateVersion: 'v1',
    recipientName: '최매니저',
    recipientId: 'recipient#192',
    recipientPhone: '+82 10-****-1180',
    status: 'fallback',
    sentAt: '2026-04-24T08:24:03+09:00',
    timeScope: '24h',
    fallbackFrom: 'alimtalk',
    detail: {
      timeline: [
        { id: 'n88322-1', title: text('알림톡 차단', 'alimtalk blocked'), detail: text('비활성 채널 프로필에서 kakao_blocked 발생', 'kakao_blocked on inactive channel profile'), timestamp: '2026-04-24T08:23:42+09:00', tone: 'warning' },
        { id: 'n88322-2', title: text('fallback 채널 선택', 'fallback channel selected'), detail: text('채널 우선순위가 LMS로 결정', 'channel rank resolved to LMS'), timestamp: '2026-04-24T08:23:44+09:00', tone: 'warning' },
        { id: 'n88322-3', title: text('LMS 전달 완료', 'lms delivered'), detail: text('제공사 접수 후 전달 완료', 'provider accepted and delivered'), timestamp: '2026-04-24T08:24:03+09:00', tone: 'success' },
      ],
      renderedVariables: {
        fallback_from: 'alimtalk',
        channel: 'lms',
      },
      providerAttempts: [
        { id: 'attempt-1', channel: 'alimtalk', status: 'fallback', provider: 'Kakao Biz', timestamp: '2026-04-24T08:23:42+09:00', detail: 'provider error kakao_blocked' },
        { id: 'attempt-2', channel: 'lms', status: 'delivered', provider: 'NCP SENS', timestamp: '2026-04-24T08:24:03+09:00', detail: text('fallback 성공', 'fallback success') },
      ],
    },
  },
  {
    id: 'delivery-88301',
    eventCode: 'procurement.best_result',
    orderId: 'order#2033',
    jobId: 'job-9789',
    resultId: 'result-58611',
    outboxId: 'outbox#77002',
    channel: 'alimtalk',
    templateName: 'procurement_best_v3',
    templateVersion: 'v5',
    recipientName: '비활성 수신자',
    recipientId: 'recipient#099',
    recipientPhone: '+82 10-****-9911',
    status: 'dead-lettered',
    sentAt: '2026-04-24T07:11:45+09:00',
    timeScope: '24h',
    fallbackFrom: null,
    detail: {
      timeline: [
        { id: 'n88301-1', title: text('발송 시도 실패', 'send attempt failed'), detail: text('비활성 수신자', 'recipient inactive'), timestamp: '2026-04-24T07:11:45+09:00', tone: 'danger' },
        { id: 'n88301-2', title: text('재시도 생략', 'retry skipped'), detail: text('동의 상태 유효하지 않음 → fallback 불가', 'consent invalid → no fallback allowed'), timestamp: '2026-04-24T07:11:46+09:00', tone: 'danger' },
        { id: 'n88301-3', title: text('DLQ 이동', 'moved to DLQ'), detail: text('운영자 개입 필요', 'operator intervention required'), timestamp: '2026-04-24T07:11:47+09:00', tone: 'danger' },
      ],
      renderedVariables: {
        reason: 'recipient inactive',
        can_fallback: false,
      },
      providerAttempts: [
        { id: 'attempt-1', channel: 'alimtalk', status: 'dead-lettered', provider: 'Kakao Biz', timestamp: '2026-04-24T07:11:45+09:00', detail: text('비활성 수신자 · fallback 동의 없음', 'inactive recipient · no fallback consent') },
      ],
    },
  },
];

export const experimentsData: ExperimentRow[] = [
  {
    id: 'exp-1042',
    type: 'uploads',
    name: '쿠팡 카테고리 크롤 · 커피머신 세정제 48종',
    source: 'coupang',
    uploader: 'parser_lab · ops_demo',
    parserVersion: 'coupang_parser · v0.4.0',
    itemCount: 48,
    acceptedCount: 42,
    compareSummary: '+₩420 median vs Naver sample 38/42',
    uploadedAt: '2026-04-24T10:02:14+09:00',
    detail: {
      isolatedSchemas: ['exp_procurement_runs', 'exp_procurement_items'],
      excludedPipelines: ['notification_dispatcher', 'savings_report', 'search_ranking'],
      retention: text('90일 · 자동 삭제', '90d · auto-purge'),
      notes: [text('ops_admin 역할 필요', 'requires ops_admin role'), text('모든 행에 EXPERIMENT 태그 지정', 'tagged EXPERIMENT on every row')],
      comparisonMetrics: [
        { id: 'cmp-1', label: text('중앙값 ₩/개', 'Median ₩/unit'), leftValue: '₩7,420', rightValue: '₩7,000', delta: '+₩420 (+6.0%)' },
        { id: 'cmp-2', label: text('커버리지', 'Coverage'), leftValue: '42 / 48', rightValue: '38 / 42', delta: '—' },
        { id: 'cmp-3', label: text('더 낮은 결과 수', 'Lower on'), leftValue: '14', rightValue: '24', delta: text('Naver 우위', 'Naver advantage') },
      ],
      rawPayload: {
        uploader: 'ops_demo',
        parserVersion: 'v0.4.0',
        experiment: true,
        gzipSizeBytes: 1200000,
      },
    },
  },
  {
    id: 'exp-1041',
    type: 'parse-runs',
    name: '쿠팡 단일 상품 · 에스프레소 머신 필터 캡 + 가스켓',
    source: 'coupang',
    uploader: 'parser_lab · ops_demo',
    parserVersion: 'coupang_parser · v0.4.0',
    itemCount: 1,
    acceptedCount: 0,
    compareSummary: 'PARSER_FAIL · option_text missing',
    uploadedAt: '2026-04-24T09:48:01+09:00',
    detail: {
      isolatedSchemas: ['exp_procurement_runs'],
      excludedPipelines: ['notification_dispatcher', 'savings_report'],
      retention: text('90일 · 자동 삭제', '90d · auto-purge'),
      notes: [text('단일 URL 스모크 테스트', 'single URL smoke test'), text('파서 회귀 검토용 저장', 'saved for parser regression review')],
      comparisonMetrics: [],
      rawPayload: {
        pageTemplateChanged: true,
        failure: 'option_text missing',
      },
    },
  },
  {
    id: 'exp-1040',
    type: 'compare',
    name: 'Naver vs Coupang 듀얼 비교 · 일회용컵 12oz',
    source: 'dual',
    uploader: 'parser_lab · ops_demo',
    parserVersion: 'dual_compare · v0.1.0',
    itemCount: 40,
    acceptedCount: 34,
    compareSummary: 'naver lower · 14 / 17 pairs',
    uploadedAt: '2026-04-24T09:11:02+09:00',
    detail: {
      isolatedSchemas: ['exp_compare_runs'],
      excludedPipelines: ['notification_dispatcher', 'savings_report', 'search_ranking'],
      retention: text('90일 · 자동 삭제', '90d · auto-purge'),
      notes: [text('관찰 전용', 'observational only'), text('운영 best_result를 갱신하지 않음', 'does not update production best_result')],
      comparisonMetrics: [
        { id: 'cmp-1', label: text('승인된 쌍', 'Accepted pairs'), leftValue: '17', rightValue: '17', delta: text('동일 표본 크기', 'equal sample size') },
        { id: 'cmp-2', label: text('중앙값 차이', 'Median delta'), leftValue: 'Coupang +6.4%', rightValue: text('Naver 기준선', 'Naver baseline'), delta: text('Naver가 더 낮음', 'Naver lower') },
      ],
      rawPayload: {
        source: 'dual',
        comparePairs: 17,
      },
    },
  },
  {
    id: 'exp-1037',
    type: 'regressions',
    name: '쿠팡 파서 회귀 테스트 · 고정 URL 50건',
    source: 'coupang',
    uploader: 'ci_runner · parser_qa_bot',
    parserVersion: 'coupang_parser · v0.4.0 → v0.4.1-rc',
    itemCount: 50,
    acceptedCount: 48,
    compareSummary: '2 regressions · option_text empty on variant pages',
    uploadedAt: '2026-04-24T04:00:00+09:00',
    detail: {
      isolatedSchemas: ['exp_regression_runs'],
      excludedPipelines: ['notification_dispatcher', 'savings_report'],
      retention: text('30일 · CI fixture', '30d · CI fixture'),
      notes: [text('월 1회 자동 실행', 'auto-run monthly'), text('회귀 증가 시 파서 릴리스 차단', 'blocks parser release if regressions increase')],
      comparisonMetrics: [
        { id: 'cmp-1', label: text('통과 fixture', 'Passing fixtures'), leftValue: '48 / 50', rightValue: text('기준선 50 / 50', 'baseline 50 / 50'), delta: text('회귀 2건', '-2 regressions') },
      ],
      rawPayload: {
        fixtureCount: 50,
        regressions: 2,
      },
    },
  },
];

export const viewDescriptions = {
  jobs: { eyebrow: 'OPS', descriptionKey: 'jobs.description' },
  results: { eyebrow: 'PROCUREMENT', descriptionKey: 'results.description' },
  notifications: { eyebrow: 'NOTI-FIRST', descriptionKey: 'notifications.description' },
  experiments: { eyebrow: 'INTERNAL', descriptionKey: 'experiments.description' },
} as const satisfies Record<ViewId, { eyebrow: string; descriptionKey: string }>;
